# Generated by Django 5.1.6 on 2026-02-14 07:40

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_rejectionreason_tag_candidatenote_applicationtag'),
        ('jobs', '0002_requisitionapproval'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardCriterion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('technical', 'Technical Skills'), ('communication', 'Communication'), ('problem_solving', 'Problem Solving'), ('culture_fit', 'Culture Fit'), ('leadership', 'Leadership'), ('other', 'Other')], max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
            ],
            options={
                'ordering': ['template', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('phone_screen', 'Phone Screen'), ('video', 'Video Interview'), ('onsite', 'On-site Interview'), ('panel', 'Panel Interview'), ('technical', 'Technical Interview'), ('behavioral', 'Behavioral Interview'), ('case_study', 'Case Study'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no_show', 'No Show')], default='scheduled', max_length=20)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('video_link', models.URLField(blank=True)),
                ('prep_notes_interviewer', models.TextField(blank=True)),
                ('prep_notes_candidate', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_interviews', to=settings.AUTH_USER_MODEL)),
                ('interview_plan_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='jobs.pipelinestage')),
            ],
            options={
                'ordering': ['scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('overall_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('recommendation', models.CharField(blank=True, choices=[('strong_hire', 'Strong Hire'), ('hire', 'Hire'), ('no_hire', 'No Hire'), ('strong_no_hire', 'Strong No Hire')], max_length=20, null=True)),
                ('strengths', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_draft', models.BooleanField(default=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards', to='interviews.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scorecards', to='accounts.internaluser')),
            ],
        ),
        migrations.CreateModel(
            name='ScorecardCriterionRating',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='interviews.scorecardcriterion')),
                ('scorecard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_ratings', to='interviews.scorecard')),
            ],
        ),
        migrations.CreateModel(
            name='ScorecardTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('rating_scale_min', models.IntegerField(default=1)),
                ('rating_scale_max', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scorecard_templates', to='accounts.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scorecardcriterion',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='interviews.scorecardtemplate'),
        ),
        migrations.AddField(
            model_name='interview',
            name='scorecard_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='interviews.scorecardtemplate'),
        ),
        migrations.CreateModel(
            name='Debrief',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField()),
                ('decision', models.CharField(blank=True, choices=[('advance', 'Advance to Next Stage'), ('reject', 'Reject'), ('hold', 'Hold'), ('pending', 'Pending More Feedback')], max_length=20, null=True)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debriefs', to='applications.application')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debrief_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['application', 'scheduled_at'], name='interviews__applica_2aa3a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterviewParticipant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('lead', 'Lead Interviewer'), ('shadow', 'Shadow Interviewer'), ('observer', 'Observer')], default='lead', max_length=20)),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('tentative', 'Tentative')], default='pending', max_length=20)),
                ('rsvp_at', models.DateTimeField(blank=True, null=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='interviews.interview')),
                ('interviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_participations', to='accounts.internaluser')),
            ],
            options={
                'unique_together': {('interview', 'interviewer')},
            },
        ),
        migrations.AddIndex(
            model_name='scorecard',
            index=models.Index(fields=['interview', 'is_draft'], name='interviews__intervi_67e935_idx'),
        ),
        migrations.AddIndex(
            model_name='scorecard',
            index=models.Index(fields=['interviewer', 'is_draft'], name='interviews__intervi_210bd9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='scorecard',
            unique_together={('interview', 'interviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='scorecardcriterionrating',
            unique_together={('scorecard', 'criterion')},
        ),
        migrations.AlterUniqueTogether(
            name='scorecardcriterion',
            unique_together={('template', 'order')},
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['application', 'status'], name='interviews__applica_96ea9d_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['scheduled_start'], name='interviews__schedul_d6f848_idx'),
        ),
        migrations.AddIndex(
            model_name='interview',
            index=models.Index(fields=['status'], name='interviews__status_187f27_idx'),
        ),
    ]
