# Generated by Django 5.1.6 on 2026-02-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='candidatescore',
            new_name='scoring_can_applica_4ebc3b_idx',
            old_name='scoring_application_idx',
        ),
        migrations.RenameIndex(
            model_name='candidatescore',
            new_name='scoring_can_final_s_341ad7_idx',
            old_name='scoring_final_score_idx',
        ),
    ]
