# Generated by Django 5.1.6 on 2026-02-16 12:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0002_requisitionapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='User-defined name for this search', max_length=200)),
                ('search_params', models.JSONField(default=dict, help_text='Search parameters: keywords, location, department, etc.')),
                ('alert_frequency', models.CharField(choices=[('instant', 'Instant'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('never', 'Never')], default='daily', help_text='How often to send email alerts for new matches', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this saved search')),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='Last time alerts were sent for this search', null=True)),
                ('match_count', models.IntegerField(default=0, help_text='Number of jobs currently matching this search')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='accounts.candidateprofile')),
            ],
            options={
                'verbose_name_plural': 'Saved searches',
                'db_table': 'accounts_saved_search',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('was_clicked', models.BooleanField(default=False, help_text='Whether candidate clicked through to the job')),
                ('was_applied', models.BooleanField(default=False, help_text='Whether candidate applied after receiving alert')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_sent', to='jobs.requisition')),
                ('saved_search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.savedsearch')),
            ],
            options={
                'db_table': 'accounts_job_alert',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['sent_at'], name='accounts_jo_sent_at_8c68b2_idx'), models.Index(fields=['was_clicked'], name='accounts_jo_was_cli_4ea8d5_idx')],
                'unique_together': {('saved_search', 'requisition')},
            },
        ),
    ]
