# Generated by Django 5.1.6 on 2026-02-20 05:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_savedsearch_jobalert'),
        ('jobs', '0005_rename_jobs_req_criteria_type_idx_jobs_requis_requisi_a5a429_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='accounts.candidateprofile')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_candidates', to='jobs.requisition')),
            ],
            options={
                'db_table': 'accounts_saved_job',
                'ordering': ['-created_at'],
                'unique_together': {('candidate', 'requisition')},
            },
        ),
    ]
