# Generated by Django 5.1.6 on 2026-02-14 10:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_rejectionreason_tag_candidatenote_applicationtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('technical', 'Technical Skills'), ('coding', 'Coding Challenge'), ('behavioral', 'Behavioral'), ('cognitive', 'Cognitive Ability'), ('personality', 'Personality'), ('culture_fit', 'Culture Fit'), ('custom', 'Custom')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(help_text='Instructions shown to candidate when taking assessment')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes (null if no time limit)', null=True)),
                ('passing_score', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum score to pass (e.g., 70.00)', max_digits=5, null=True)),
                ('scoring_rubric', models.JSONField(blank=True, default=dict, help_text='JSON structure defining how to score the assessment')),
                ('questions', models.JSONField(blank=True, default=list, help_text='Assessment questions and answer options (for built-in assessments)')),
                ('external_url', models.URLField(blank=True, help_text='URL for external assessment platform (e.g., HackerRank, Codility)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'assessments_template',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCheckRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_name', models.CharField(max_length=200)),
                ('reference_email', models.EmailField(max_length=254)),
                ('reference_phone', models.CharField(blank=True, max_length=50)),
                ('reference_company', models.CharField(blank=True, max_length=200)),
                ('reference_title', models.CharField(blank=True, max_length=200)),
                ('relationship', models.CharField(choices=[('manager', 'Manager/Supervisor'), ('colleague', 'Colleague/Peer'), ('direct_report', 'Direct Report'), ('client', 'Client/Customer'), ('other', 'Other')], default='manager', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('declined', 'Declined'), ('expired', 'Expired')], db_index=True, default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, help_text='When email was sent to reference', null=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Deadline for reference to respond', null=True)),
                ('questionnaire', models.JSONField(default=list, help_text='Questions to ask the reference')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this reference')),
                ('access_token', models.CharField(help_text='Unique token for reference to access form', max_length=100, unique=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_checks', to='applications.application')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_checks_requested', to='accounts.internaluser')),
            ],
            options={
                'db_table': 'assessments_reference_request',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCheckResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responses', models.JSONField(default=dict, help_text='Answers to questionnaire questions')),
                ('overall_recommendation', models.CharField(blank=True, choices=[('highly_recommend', 'Highly Recommend'), ('recommend', 'Recommend'), ('recommend_with_reservations', 'Recommend with Reservations'), ('do_not_recommend', 'Do Not Recommend'), ('no_opinion', 'No Opinion')], max_length=30, null=True)),
                ('would_rehire', models.BooleanField(blank=True, help_text='Would you hire this person again? (if former manager)', null=True)),
                ('additional_comments', models.TextField(blank=True, help_text='Additional feedback from reference')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reference_ip', models.GenericIPAddressField(blank=True, help_text='IP address of reference submitter', null=True)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='assessments.referencecheckrequest')),
            ],
            options={
                'db_table': 'assessments_reference_response',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('expired', 'Expired'), ('waived', 'Waived')], db_index=True, default='assigned', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Deadline for completion', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When candidate started the assessment', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When assessment was submitted', null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, help_text='Final score (e.g., 85.50)', max_digits=5, null=True)),
                ('responses', models.JSONField(blank=True, default=dict, help_text='Candidate responses to assessment questions')),
                ('evaluator_notes', models.TextField(blank=True, help_text='Notes from evaluator who scored the assessment')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('access_token', models.CharField(help_text='Unique token for candidate to access assessment', max_length=100, unique=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='applications.application')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments_assigned', to='accounts.internaluser')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_evaluated', to='accounts.internaluser')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='assessments.assessmenttemplate')),
            ],
            options={
                'db_table': 'assessments_assessment',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['application', 'status'], name='assessments_applica_ec3967_idx'), models.Index(fields=['access_token'], name='assessments_access__094858_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='referencecheckrequest',
            index=models.Index(fields=['application', 'status'], name='assessments_applica_c067bd_idx'),
        ),
        migrations.AddIndex(
            model_name='referencecheckrequest',
            index=models.Index(fields=['access_token'], name='assessments_access__a00a2c_idx'),
        ),
    ]
