# Generated by Django 5.1.6 on 2026-02-14 06:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requisition_id', models.CharField(help_text='Auto-generated ID, e.g. REQ-2026-001', max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('open', 'Open'), ('on_hold', 'On Hold'), ('filled', 'Filled'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship')], default='full_time', max_length=20)),
                ('remote_policy', models.CharField(choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], default='onsite', max_length=10)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('description', models.TextField(help_text='Rich text job description.')),
                ('requirements_required', models.JSONField(blank=True, default=list, help_text='List of required qualifications.')),
                ('requirements_preferred', models.JSONField(blank=True, default=list, help_text='List of preferred qualifications.')),
                ('screening_questions', models.JSONField(blank=True, default=list, help_text='Custom screening questions for applicants.')),
                ('headcount', models.PositiveIntegerField(default=1)),
                ('filled_count', models.PositiveIntegerField(default=0)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('target_fill_date', models.DateField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_requisitions', to='accounts.internaluser')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='accounts.department')),
                ('hiring_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_requisitions', to='accounts.internaluser')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='accounts.joblevel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requisitions', to='accounts.location')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_requisitions', to='accounts.internaluser')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisitions', to='accounts.team')),
            ],
            options={
                'db_table': 'jobs_requisition',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('stage_type', models.CharField(choices=[('application', 'Application'), ('screening', 'Screening'), ('phone_screen', 'Phone Screen'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('hired', 'Hired'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('auto_actions', models.JSONField(blank=True, default=list, help_text='Actions triggered when a candidate enters this stage.')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='jobs.requisition')),
            ],
            options={
                'db_table': 'jobs_pipeline_stage',
                'ordering': ['requisition', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['status', '-created_at'], name='jobs_requis_status_2442b1_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['department', 'status'], name='jobs_requis_departm_e880ce_idx'),
        ),
        migrations.AddIndex(
            model_name='requisition',
            index=models.Index(fields=['recruiter', 'status'], name='jobs_requis_recruit_2e762b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pipelinestage',
            unique_together={('requisition', 'order')},
        ),
    ]
