# Generated by Django 5.1.6 on 2026-02-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_requisitionapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisition',
            name='salary_currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
    ]
