# Generated by Django 5.1.6 on 2026-02-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_requisitioncriteria'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='requisitioncriteria',
            new_name='jobs_requis_requisi_a5a429_idx',
            old_name='jobs_req_criteria_type_idx',
        ),
    ]
