# Generated by Django 5.1.6 on 2026-02-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_rename_jobs_req_criteria_type_idx_jobs_requis_requisi_a5a429_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisition',
            name='application_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for submitting applications. Shown as "Closes in X days" on job listings.', null=True),
        ),
    ]
