# Generated by Django 5.1.6 on 2026-02-14 07:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('application_id', models.CharField(help_text='Auto-generated, e.g. APP-2026-00001', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='applied', max_length=20)),
                ('source', models.CharField(choices=[('direct', 'Direct'), ('career_site', 'Career Site'), ('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('referral', 'Referral'), ('agency', 'Agency'), ('other', 'Other')], default='career_site', max_length=20)),
                ('resume_snapshot', models.JSONField(blank=True, help_text='Snapshot of resume data at time of application.', null=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('screening_responses', models.JSONField(blank=True, default=dict, help_text='Answers to requisition screening questions.')),
                ('is_starred', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, max_length=200)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('hired_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.candidateprofile')),
                ('current_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.pipelinestage')),
                ('referrer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_applications', to='accounts.internaluser')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.requisition')),
            ],
            options={
                'db_table': 'applications_application',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('application.created', 'Application Created'), ('application.stage_changed', 'Stage Changed'), ('application.status_changed', 'Status Changed'), ('application.withdrawn', 'Withdrawn'), ('application.rejected', 'Rejected'), ('application.hired', 'Hired'), ('note.added', 'Note Added'), ('email.sent', 'Email Sent')], max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.application')),
                ('from_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.pipelinestage')),
                ('to_stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='jobs.pipelinestage')),
            ],
            options={
                'db_table': 'applications_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['requisition', 'status'], name='application_requisi_ee405f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', '-applied_at'], name='application_candida_2dbb8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('candidate', 'requisition'), name='unique_candidate_requisition'),
        ),
        migrations.AddIndex(
            model_name='applicationevent',
            index=models.Index(fields=['application', '-created_at'], name='application_applica_4d01a1_idx'),
        ),
    ]
