# Generated by Django 5.1.6 on 2026-02-14 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectionReason',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'applications_rejection_reason',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#6366f1', help_text='Hex colour code.', max_length=7)),
            ],
            options={
                'db_table': 'applications_tag',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CandidateNote',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('is_private', models.BooleanField(default=False, help_text='Private notes are visible only to the author.')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applications.application')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidate_notes', to='accounts.internaluser')),
            ],
            options={
                'db_table': 'applications_candidate_note',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['application', '-created_at'], name='application_applica_f8b33c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApplicationTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_tags', to='applications.application')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_tags', to='applications.tag')),
            ],
            options={
                'db_table': 'applications_application_tag',
                'unique_together': {('application', 'tag')},
            },
        ),
    ]
