# Generated by Django 5.1.6 on 2026-02-14 12:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_rejectionreason_tag_candidatenote_applicationtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentPool',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_dynamic', models.BooleanField(default=False, help_text='Dynamic pools auto-update based on search_criteria.')),
                ('search_criteria', models.JSONField(blank=True, default=dict, help_text='Search filters for dynamic pools (skills, experience, location, etc.).')),
                ('candidates', models.ManyToManyField(blank=True, related_name='talent_pools', to='accounts.candidateprofile')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_talent_pools', to='accounts.internaluser')),
            ],
            options={
                'db_table': 'applications_talent_pool',
                'ordering': ['name'],
            },
        ),
    ]
