# Generated by Django 5.1.6 on 2026-02-16 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_savedsearch_jobalert'),
        ('applications', '0003_talentpool'),
        ('jobs', '0002_requisitionapproval'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='application',
            name='unique_candidate_requisition',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('hired', 'Hired'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='applied', max_length=20),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['candidate', 'status'], name='candidate_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft'), _negated=True), fields=('candidate', 'requisition'), name='unique_candidate_requisition_submitted'),
        ),
    ]
