# Generated by Django 5.1.6 on 2026-02-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_application_unique_candidate_requisition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='withdrawal_reason',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
