# Generated by Django 5.1.6 on 2026-02-15 08:04

import django.db.models.deletion
import encrypted_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_requisitionapproval'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('indeed', 'Indeed'), ('linkedin', 'LinkedIn'), ('glassdoor', 'Glassdoor'), ('bamboo_hr', 'BambooHR'), ('workday', 'Workday'), ('adp', 'ADP'), ('custom', 'Custom Integration')], help_text='Integration provider', max_length=50)),
                ('category', models.CharField(choices=[('job_board', 'Job Board'), ('hris', 'HRIS'), ('ats', 'Applicant Tracking System'), ('custom', 'Custom')], help_text='Integration category', max_length=50)),
                ('name', models.CharField(help_text='User-friendly integration name', max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Enable or disable integration')),
                ('config', encrypted_fields.fields.EncryptedTextField(help_text='Encrypted JSON configuration (API keys, endpoints, settings)')),
                ('oauth_token', encrypted_fields.fields.EncryptedTextField(blank=True, help_text='OAuth access token (encrypted)', null=True)),
                ('oauth_refresh_token', encrypted_fields.fields.EncryptedTextField(blank=True, help_text='OAuth refresh token (encrypted)', null=True)),
                ('oauth_expires_at', models.DateTimeField(blank=True, help_text='OAuth token expiration timestamp', null=True)),
                ('last_sync', models.DateTimeField(blank=True, help_text='Last successful sync timestamp', null=True)),
                ('sync_status', models.CharField(choices=[('idle', 'Idle'), ('syncing', 'Syncing'), ('success', 'Success'), ('error', 'Error')], db_index=True, default='idle', help_text='Current sync status', max_length=20)),
                ('error_log', models.TextField(blank=True, help_text='Last error message')),
                ('failure_count', models.IntegerField(default=0, help_text='Consecutive failure count for circuit breaker')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Provider-specific metadata')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', 'sync_status'], name='integration_is_acti_1f4014_idx'), models.Index(fields=['category'], name='integration_categor_6c4bea_idx')],
                'unique_together': {('provider', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='Webhook endpoint URL to POST events to', max_length=500)),
                ('secret', encrypted_fields.fields.EncryptedCharField(help_text='HMAC signing secret (encrypted)', max_length=255)),
                ('events', models.JSONField(default=list, help_text='List of event types to send to this endpoint')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Enable or disable webhook delivery')),
                ('failure_count', models.IntegerField(db_index=True, default=0, help_text='Consecutive delivery failure count')),
                ('last_success', models.DateTimeField(blank=True, help_text='Last successful delivery timestamp', null=True)),
                ('last_failure', models.DateTimeField(blank=True, help_text='Last failed delivery timestamp', null=True)),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Custom HTTP headers to include in requests')),
                ('integration', models.ForeignKey(blank=True, help_text='Associated integration (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='integrations.integration')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='Event type (e.g., application.created)', max_length=100)),
                ('payload', models.JSONField(help_text='Full event payload sent to webhook')),
                ('response_status', models.IntegerField(blank=True, help_text='HTTP response status code', null=True)),
                ('response_body', models.TextField(blank=True, help_text='Response body from webhook endpoint')),
                ('delivered_at', models.DateTimeField(blank=True, help_text='Successful delivery timestamp', null=True)),
                ('attempts', models.IntegerField(default=1, help_text='Number of delivery attempts')),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('endpoint', models.ForeignKey(help_text='Target webhook endpoint', on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='integrations.webhookendpoint')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobBoardPosting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(help_text='Job ID from external job board', max_length=255)),
                ('posted_at', models.DateTimeField(auto_now_add=True, help_text='Initial posting timestamp')),
                ('last_synced', models.DateTimeField(blank=True, help_text='Last sync with job board', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('closed', 'Closed'), ('error', 'Error')], db_index=True, default='draft', help_text='Posting status', max_length=20)),
                ('url', models.URLField(blank=True, help_text='Public job posting URL on the board', max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Board-specific posting data')),
                ('integration', models.ForeignKey(help_text='Job board integration used', on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='integrations.integration')),
                ('requisition', models.ForeignKey(help_text='Job requisition posted to board', on_delete=django.db.models.deletion.CASCADE, related_name='board_postings', to='jobs.requisition')),
            ],
            options={
                'ordering': ['-posted_at'],
                'indexes': [models.Index(fields=['status', '-posted_at'], name='integration_status_a3f44a_idx'), models.Index(fields=['integration', 'external_id'], name='integration_integra_454a0f_idx')],
                'unique_together': {('requisition', 'integration')},
            },
        ),
        migrations.AddIndex(
            model_name='webhookendpoint',
            index=models.Index(fields=['is_active', 'failure_count'], name='integration_is_acti_83e65d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['event_type', '-created_at'], name='integration_event_t_e3e952_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['endpoint', '-created_at'], name='integration_endpoin_14e898_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdelivery',
            index=models.Index(fields=['delivered_at'], name='integration_deliver_092f08_idx'),
        ),
    ]
