# Generated by Django 5.1.6 on 2026-02-15 06:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0003_talentpool'),
        ('offers', '0003_alter_offer_offer_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending Start'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('start_date', models.DateField(help_text='First day of work')),
                ('access_token', models.CharField(help_text='Token for candidate to access onboarding portal', max_length=64, unique=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_plan', to='applications.application')),
                ('buddy', models.ForeignKey(blank=True, help_text='Buddy/mentor assigned to new hire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_buddy_for', to='accounts.internaluser')),
                ('hr_contact', models.ForeignKey(blank=True, help_text='HR contact for onboarding questions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_hr_contact_for', to='accounts.internaluser')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_plan', to='offers.offer')),
            ],
            options={
                'db_table': 'onboarding_plan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('i9', 'I-9 Form'), ('w4', 'W-4 Tax Form'), ('direct_deposit', 'Direct Deposit Form'), ('emergency_contact', 'Emergency Contact Form'), ('signed_offer', 'Signed Offer Letter'), ('nda', 'Non-Disclosure Agreement'), ('handbook_acknowledgment', 'Handbook Acknowledgment'), ('equipment_agreement', 'Equipment Agreement'), ('photo_id', 'Photo ID'), ('work_authorization', 'Work Authorization'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='onboarding/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploaded', 'Uploaded'), ('reviewed', 'Reviewed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_documents_reviewed', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.onboardingplan')),
            ],
            options={
                'db_table': 'onboarding_document',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTask',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('admin', 'Administrative'), ('equipment', 'Equipment Setup'), ('access', 'System Access'), ('training', 'Training'), ('meeting', 'Meetings'), ('document', 'Documentation'), ('other', 'Other')], default='other', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='User responsible for completing this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_tasks', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_tasks_completed', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='onboarding.onboardingplan')),
            ],
            options={
                'db_table': 'onboarding_task',
                'ordering': ['order', 'due_date'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('tasks', models.JSONField(default=list, help_text='List of task templates with title, description, category, days_offset')),
                ('required_documents', models.JSONField(default=list, help_text='List of required document types')),
                ('forms', models.JSONField(default=list, help_text='List of required form types')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_templates', to='accounts.department')),
                ('job_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_templates', to='accounts.joblevel')),
            ],
            options={
                'db_table': 'onboarding_template',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='onboardingplan',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='onboarding.onboardingtemplate'),
        ),
        migrations.CreateModel(
            name='OnboardingForm',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_type', models.CharField(choices=[('equipment_preferences', 'Equipment Preferences'), ('workspace_preferences', 'Workspace Preferences'), ('emergency_contact', 'Emergency Contact Information'), ('dietary_restrictions', 'Dietary Restrictions'), ('accessibility_needs', 'Accessibility Needs'), ('parking', 'Parking Request'), ('benefits_enrollment', 'Benefits Enrollment'), ('other', 'Other')], max_length=50)),
                ('data', models.JSONField(default=dict, help_text='Form responses as key-value pairs')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_forms_submitted', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='onboarding.onboardingplan')),
            ],
            options={
                'db_table': 'onboarding_form',
                'ordering': ['-submitted_at'],
                'unique_together': {('plan', 'form_type')},
            },
        ),
    ]
