# Generated by Django 5.1.6 on 2026-02-14 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_rejectionreason_tag_candidatenote_applicationtag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('category', models.CharField(choices=[('application', 'Application'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejection', 'Rejection'), ('onboarding', 'Onboarding'), ('general', 'General')], max_length=50)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField()),
                ('body_text', models.TextField()),
                ('variables', models.JSONField(default=dict, help_text='Available merge fields for this template (e.g., {"candidate_name": "string", "job_title": "string"})')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('department', models.ForeignKey(blank=True, help_text='If set, template is department-specific', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_templates', to='accounts.department')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.EmailField(max_length=254)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=500)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('bounced', 'Bounced'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, help_text='External email provider message ID', max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata (merge fields used, provider response, etc.)')),
                ('application', models.ForeignKey(blank=True, help_text='If email is related to an application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='applications.application')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='communications.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('application', 'Application Update'), ('interview', 'Interview'), ('scorecard', 'Scorecard Reminder'), ('approval', 'Approval Request'), ('mention', 'Mention'), ('system', 'System')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, help_text='Internal app link (e.g., /applications/123)', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional context (application_id, interview_id, etc.)')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emailtemplate',
            index=models.Index(fields=['category', 'is_active'], name='communicati_categor_0b0d1a_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['recipient', '-created_at'], name='communicati_recipie_1e3322_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['status', '-created_at'], name='communicati_status_4c74ed_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['application', '-created_at'], name='communicati_applica_0b7785_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='communicati_recipie_df41d2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='communicati_recipie_fc8f0b_idx'),
        ),
    ]
