# Generated by Django 5.1.6 on 2026-02-14 09:01

import django.db.models.deletion
import encrypted_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('applications', '0002_rejectionreason_tag_candidatenote_applicationtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_id', models.CharField(help_text='Auto-generated ID, e.g. OFR-2026-001', max_length=20, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('sent', 'Sent to Candidate'), ('viewed', 'Viewed by Candidate'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn')], db_index=True, default='draft', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('base_salary', encrypted_fields.fields.EncryptedTextField(help_text='Encrypted salary amount (stored as string)')),
                ('salary_currency', models.CharField(default='USD', max_length=3)),
                ('salary_frequency', models.CharField(choices=[('hourly', 'Hourly'), ('annual', 'Annual')], default='annual', max_length=10)),
                ('bonus', encrypted_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted bonus amount (stored as string)')),
                ('equity', models.CharField(blank=True, help_text='Stock options/RSUs description', max_length=200)),
                ('sign_on_bonus', encrypted_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted sign-on bonus (stored as string)')),
                ('relocation', encrypted_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted relocation amount (stored as string)')),
                ('start_date', models.DateField()),
                ('expiration_date', models.DateField(help_text='Date by which candidate must accept/decline')),
                ('offer_letter_pdf', models.FileField(blank=True, help_text='Generated offer letter PDF', upload_to='offers/%Y/%m/')),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True)),
                ('esignature_envelope_id', models.CharField(blank=True, help_text='DocuSign/HelloSign envelope ID', max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='applications.application')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_offers', to='accounts.internaluser')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='accounts.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='accounts.joblevel')),
                ('reporting_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_reports_offers', to='accounts.internaluser')),
            ],
            options={
                'db_table': 'offers_offer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferApproval',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(help_text='Order in approval chain (0-indexed)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('comments', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_approvals', to='accounts.internaluser')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='offers.offer')),
            ],
            options={
                'db_table': 'offers_approval',
                'ordering': ['offer', 'order'],
            },
        ),
        migrations.CreateModel(
            name='OfferNegotiationLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_request', models.TextField(help_text='What the candidate is requesting')),
                ('internal_response', models.TextField(blank=True, help_text='Internal team response/decision')),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('revised_offer', 'Revised Offer Sent')], default='pending', max_length=20)),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offer_negotiations', to='accounts.internaluser')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='negotiation_logs', to='offers.offer')),
            ],
            options={
                'db_table': 'offers_negotiation_log',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status', '-created_at'], name='offers_offe_status_21eb17_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['application', 'version'], name='offers_offe_applica_d36198_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='offerapproval',
            unique_together={('offer', 'order')},
        ),
    ]
