# Generated by Django 5.1.6 on 2026-02-14 09:15

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='bonus',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted bonus amount (stored as string)', null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='relocation',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted relocation amount (stored as string)', null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sign_on_bonus',
            field=encrypted_fields.fields.EncryptedTextField(blank=True, help_text='Encrypted sign-on bonus (stored as string)', null=True),
        ),
    ]
