# Generated by Django 5.1.6 on 2026-02-14 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_bonus_alter_offer_relocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='offer_id',
            field=models.CharField(db_index=True, help_text='Auto-generated ID, e.g. OFR-2026-001 (can have multiple versions)', max_length=20),
        ),
    ]
