# Generated by Django 5.1.6 on 2026-02-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_alter_offer_offer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='salary_currency',
            field=models.CharField(default='ZAR', max_length=3),
        ),
    ]
