# Generated by Django 5.1.6 on 2026-02-14 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.CharField(max_length=50)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.CharField(max_length=255)),
                ('changes', models.JSONField(blank=True, help_text='Before/after snapshot for update operations.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_audit_log',
                'ordering': ['-timestamp'],
                'permissions': [('export_auditlog', 'Can export audit logs')],
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='compliance__actor_i_05762e_idx'), models.Index(fields=['resource_type', 'resource_id'], name='compliance__resourc_bb2fa9_idx')],
            },
        ),
    ]
