# Generated by Django 5.1.6 on 2026-02-15 05:52

import django.db.models.deletion
import encrypted_fields.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('compliance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataRetentionPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('candidate_application', 'Candidate Applications'), ('candidate_profile', 'Candidate Profiles'), ('assessment_results', 'Assessment Results'), ('interview_notes', 'Interview Notes'), ('communication_logs', 'Communication Logs'), ('audit_logs', 'Audit Logs')], max_length=50, unique=True)),
                ('retention_days', models.PositiveIntegerField(help_text='Number of days to retain data after creation/last update')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this policy is currently enforced')),
                ('grace_period_days', models.PositiveIntegerField(default=30, help_text='Grace period before data is actually deleted')),
                ('description', models.TextField(blank=True, help_text='Description of this retention policy')),
                ('last_executed', models.DateTimeField(blank=True, help_text='Last time this policy was executed', null=True)),
            ],
            options={
                'verbose_name': 'Data Retention Policy',
                'verbose_name_plural': 'Data Retention Policies',
                'db_table': 'compliance_data_retention_policy',
                'ordering': ['data_type'],
            },
        ),
        migrations.CreateModel(
            name='EEOData',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gender', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Self-identified gender (optional)', max_length=100)),
                ('race_ethnicity', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Self-identified race/ethnicity (optional)', max_length=200)),
                ('veteran_status', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Protected veteran status (optional)', max_length=100)),
                ('disability_status', encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Disability status (optional)', max_length=100)),
                ('consent_given', models.BooleanField(default=True, help_text='Candidate consented to provide this data')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eeo_data', to='accounts.candidateprofile')),
            ],
            options={
                'verbose_name': 'EEO Data',
                'verbose_name_plural': 'EEO Data',
                'db_table': 'compliance_eeo_data',
                'permissions': [('view_eeo_reports', 'Can view aggregated EEO reports'), ('export_eeo_data', 'Can export EEO compliance reports')],
            },
        ),
        migrations.CreateModel(
            name='AnonymizationRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.UUIDField(help_text='Original candidate UUID (preserved for audit trail)')),
                ('candidate_email_hash', models.CharField(help_text='SHA-256 hash of email for duplicate detection', max_length=64)),
                ('anonymized_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(help_text='Reason for anonymization (user request, retention policy, etc.)', max_length=200)),
                ('applications_count', models.IntegerField(default=0, help_text='Number of applications at time of anonymization')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional anonymization context')),
                ('anonymized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymizations_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_anonymization_record',
                'ordering': ['-anonymized_at'],
                'indexes': [models.Index(fields=['-anonymized_at'], name='compliance__anonymi_72bcbb_idx'), models.Index(fields=['candidate_id'], name='compliance__candida_ee1824_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consent_type', models.CharField(choices=[('data_processing', 'Data Processing'), ('marketing', 'Marketing Communications'), ('data_sharing', 'Data Sharing with Partners'), ('eeo_collection', 'EEO Data Collection')], max_length=50)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address when consent was given', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_consent_record',
                'ordering': ['-given_at'],
                'indexes': [models.Index(fields=['user', 'consent_type'], name='compliance__user_id_ccdec3_idx'), models.Index(fields=['-given_at'], name='compliance__given_a_1f93f9_idx')],
            },
        ),
    ]
