# Generated by Django 5.1.6 on 2026-02-15 05:57

import encrypted_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_dataretentionpolicy_eeodata_anonymizationrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eeodata',
            name='disability_status',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Disability status (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eeodata',
            name='gender',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Self-identified gender (optional)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='eeodata',
            name='race_ethnicity',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Self-identified race/ethnicity (optional)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='eeodata',
            name='veteran_status',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, help_text='Protected veteran status (optional)', max_length=100, null=True),
        ),
    ]
